name: base_package
description: base package, widget, extension, utils recycle
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dropdown_below: ^1.0.3
  flutter_lints: ^2.0.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.2
  flutter_svg: ^1.1.4
  image_picker: ^0.8.6
  intl: ^0.17.0
  url_launcher: ^6.1.6
  flutter_cache_manager: ^3.1.2
  pull_to_refresh_flutter3: ^2.0.1
  device_info_plus: ^8.1.0
  fluttertoast: ^8.1.3
  app_settings: ^4.1.8
  permission_handler:
  carousel_slider: ^4.1.1

  json_annotation: ^4.8.0
  logger: ^1.1.0
  equatable: ^2.0.5
  collection:
  dropdown_button2: ^1.9.2
  get_it:
  dio: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  copy_with_extension_gen: ^5.0.0
  build_runner: any
  json_serializable: ^6.4.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
